version: "3.9"

services:
  memory-db:
    image: postgres:16
    container_name: memory-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: memory_db
      POSTGRES_USER: memory_db_user
      POSTGRES_PASSWORD: "kp&1V25Wg$"
    ports:
      - "14013:5432"
    volumes:
      - memory_db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memory_db_user -d memory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  memory_db_data: